import {
  FormConfig,
  getFormData,
  useGetFormData,
  useSubmitFormData,
  Form,
  FormValues,
} from "@/features/dynamicForm";
import { Container, Text } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";

const formName = "personalDetails";

export default function Home({
  formData,
}: {
  formData: { formName: string; data: FormConfig };
}) {
  const router = useRouter();
  const { data } = useGetFormData(formName, formData);

  const onSuccess = () => {
    router.push("/thanks");
  };

  const {
    mutate,
    isError: submitError,
    isPending: submitLoading,
  } = useSubmitFormData(formName, onSuccess);

  const onSubmit = (data: FormValues) => {
    mutate(data);
  };

  return (
    <>
      <Head>
        <title>Dynamic Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <Container maxW="xl" mt="40">
            <Form
              formData={data.data}
              onSubmit={onSubmit}
              isLoading={submitLoading}
            />

            {submitError && (
              <Text mt="3" color="red">
                Sorry something went wrong during submission, please try again
              </Text>
            )}
          </Container>
        </main>
      </div>
    </>
  );
}

// Already on server don't need to make a network request - Added her to simulate external API
export const getServerSideProps = async () => {
  const formData = await getFormData(formName);
  return { props: { formData } };
};
