import { Container, Text } from "@chakra-ui/react";
import Head from "next/head";

export default function Thanks() {
  return (
    <>
      <Head>
        <title>Thanks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <Container maxW="xl" mt="40">
            <Text>Thanks your form was submitted</Text>
          </Container>
        </main>
      </div>
    </>
  );
}
